# Generated by Django 5.0 on 2023-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_438', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='group_num',
            field=models.IntegerField(default=1),
        ),
    ]
