# Generated by Django 5.0 on 2023-12-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_438', '0003_delete_kid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('group_number', models.IntegerField()),
            ],
        ),
    ]
